name: Coletor de Vídeos do YouTube

on:
  schedule:
    - cron: '0 8,20 * * *'  # Executa às 8h e 20h todos os dias
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

- name: Instalar dependências
  run: |
    pip install notebook pandas requests google-api-python-client


      - name: Executar coletor
        run: python3 main.py

      - name: Commit e push do CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dados_videos.csv
          git commit -m "Atualização automática dos dados"
          git push
