name: Executar Coleta de Vídeos do YouTube

on:
  schedule:
    - cron: '0 8,20 * * *'  # Executa às 8h e 20h todos os dias
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}  # Chave da API do YouTube
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar coletor
        run: python3 main.py

      - name: Verificar se o CSV foi gerado
        run: |
          if [ ! -f *.csv ]; then
            echo "Nenhum arquivo CSV foi gerado."
            exit 1
          fi

- name: Debug Info
  run: |
    git remote -v
    git config --list

      - name: Commit e push do CSV
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENV2 }}  # Use o nome do segredo que você criou
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "Atualização automática dos dados"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          git push origin main
